on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'

      - run: flutter pub get
      - run: flutter build windows

      - name: Install yq
        run: winget install yq -e

      - name: Compress archive
        id: compress
        run: |
          $VERSION=$(yq -r ".version" pubspec.yaml | % { $_ -replace '\+.+', '' })
          $FILENAME="dqm_installer_flt_${VERSION}_windows.zip"
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT
          
          cd build\windows\runner
          Move-Item -Path release -Destination dqm_installer_flt
          Compress-Archive -DestinationPath ..\..\..\$FILENAME -Path dqm_installer_flt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            ${{ steps.compress.outputs.filename }}

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'

      - name: Import Apple provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n "${{ secrets.PROVISIONING_PROFILE_BASE64 }}" | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/DQM_Installer_FLT.provisionprofile

      - name: Import code-signing certificate
        uses: Apple-Actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.CERT_P12_BASE64 }}
          p12-password: ${{ secrets.CERT_P12_PASS }}

      - name: Import App Store Connect keychain
        run: |
          echo -n "${{ secrets.APP_STORE_CONNECT_KEY }}" > AuthKey_${{ secrets.APP_STORE_CONNECT_KEY_ID }}.p8
          xcrun notarytool store-credentials "App Store Connect Profile" \
            --key AuthKey_${{ secrets.APP_STORE_CONNECT_KEY_ID }}.p8 \
            --key-id ${{ secrets.APP_STORE_CONNECT_KEY_ID }} \
            --issuer ${{ secrets.APP_STORE_CONNECT_KEY_ISSUER }}

      - run: flutter pub get
      - name: Archive macOS build
        run: |
          flutter build macos --config-only
          xcodebuild -workspace ./macos/Runner.xcworkspace -scheme Runner archive

      - uses: actions/upload-artifact@v3
        with:
          name: dqm_installer_flt__macos
          path: build/macos/notarized/dqm_installer_flt.dmg

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get install -y ninja-build libgtk-3-dev

      - run: flutter pub get
      - run: flutter build linux

      - run: |
          cd build/linux/x64/release
          mv bundle dqm_installer_flt
          zip -r linux_build.zip ./dqm_installer_flt
      - uses: actions/upload-artifact@v3
        with:
          name: dqm_installer_flt__linux
          path: build/linux/x64/release/linux_build.zip