on:
  push:
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'

      - run: flutter pub get
      - run: flutter build windows

      - run: Compress-Archive -DestinationPath windows_build.zip -Path build\windows\runner\release\*
      - uses: actions/upload-artifact@v3
        with:
          name: dqm_installer_flt__windows
          path: windows_build.zip

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'

      - name: Import Apple provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n "${{ secrets.PROVISIONING_PROFILE_BASE64 }}" | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/DQM_Installer_FLT.provisionprofile

      - name: Import code-signing certificate
        uses: Apple-Actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.CERT_P12_BASE64 }}
          p12-password: ${{ secrets.CERT_P12_PASS }}

      - run: flutter pub get
      - run: flutter build macos

      - run: zip -r macos_build.zip build/macos/Build/Products/Release/dqm_installer_flt.app
      - uses: actions/upload-artifact@v3
        with:
          name: dqm_installer_flt__macos
          path: macos_build.zip

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get install -y ninja-build libgtk-3-dev

      - run: flutter pub get
      - run: flutter build linux

      - run: zip -r linux_build.zip build/linux/x64/release/bundle/*
      - uses: actions/upload-artifact@v3
        with:
          name: dqm_installer_flt__linux
          path: linux_build.zip